name: Base16 CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup Rust
        uses: hecrj/setup-rust-action@v2
        with:
          rust-version: stable
      - uses: actions/checkout@v4
      - name: Fetch Trunk
        uses: jetli/trunk-action@v0.4.0
        with:
          version: 'latest'
      - run: cargo build --verbose --all-features
      - run: cargo test --verbose --all-features
      - run: cargo doc --verbose
      - run: cargo doc --verbose --all-features
